application: bikeshareapp
version: 1
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: webapp2
  version: "2.5.1"                                                              
- name: jinja2                                                                  
  version: latest                                                               
- name: markupsafe                                                              
  version: latest

builtins:
- deferred: on

inbound_services:
- mail

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /admin/*
  script: bikeshareapp.app
  login: admin
- url: /_ah/mail/.+
  script: inboundmail.app
  login: admin
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
- url: /static/images/*
  static_dir: static/images
- url: /.*
  script: bikeshareapp.app