application: bikeshareapp
version: 1
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: webapp2
  version: "2.5.1"                                                              
- name: jinja2                                                                  
  version: latest                                                               
- name: markupsafe                                                              
  version: latest

builtins:
- deferred: on

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: bikeshareapp.app
- url: /updatestatus
  script: bikeshareapp.app
  login: admin
- url: /updateall
  script: bikeshareapp.app
  login: admin
- url: /.*
  script: bikeshareapp.app